/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author nandocode
 */
public class jfPrincipal extends javax.swing.JFrame {

    private boolean operacionRealizada = true;

    Operaciones operacion = new Operaciones();

    /**
     * Creates new form jfPrincipal
     */
    public jfPrincipal() {

        initComponents();
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);

    }

    private void cerrar() {
        // Un confirmacion al cerrar una ventana 
        Object[] opciones = {"Aceptar", "Cancelar"};
        int eleccion = JOptionPane.showOptionDialog(rootPane, "En realidad desea cerrar la aplicacion", "Mensaje de Confirmacion",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, opciones, "Aceptar");
        if (eleccion == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtPantalla = new javax.swing.JTextField();
        btnUno = new javax.swing.JButton();
        btnDos = new javax.swing.JButton();
        btnTres = new javax.swing.JButton();
        btnC = new javax.swing.JButton();
        btnCuatro = new javax.swing.JButton();
        btnCinco = new javax.swing.JButton();
        btnSeis = new javax.swing.JButton();
        btnSiete = new javax.swing.JButton();
        btnOcho = new javax.swing.JButton();
        btnNueve = new javax.swing.JButton();
        btnSuma = new javax.swing.JButton();
        btnMultiplicacion = new javax.swing.JButton();
        btnDividir = new javax.swing.JButton();
        btnCero = new javax.swing.JButton();
        btnResta = new javax.swing.JButton();
        btnResultado = new javax.swing.JButton();
        btnBorrarUnDigito = new javax.swing.JButton();
        btnPuntoDecimal = new javax.swing.JButton();
        lblSimbolo = new javax.swing.JLabel();
        FondoColor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPantalla.setFont(new java.awt.Font("Arial", 0, 19)); // NOI18N
        txtPantalla.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPantalla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPantallaKeyTyped(evt);
            }
        });
        jPanel1.add(txtPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 38, 269, 85));

        btnUno.setBackground(new java.awt.Color(254, 254, 254));
        btnUno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/num1.png"))); // NOI18N
        btnUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnoActionPerformed(evt);
            }
        });
        jPanel1.add(btnUno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 48, 48));

        btnDos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/num2.png"))); // NOI18N
        btnDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDosActionPerformed(evt);
            }
        });
        jPanel1.add(btnDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 48, 48));

        btnTres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/num3.png"))); // NOI18N
        btnTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTresActionPerformed(evt);
            }
        });
        jPanel1.add(btnTres, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 48, 48));

        btnC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/c.png"))); // NOI18N
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });
        jPanel1.add(btnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 49, 49));

        btnCuatro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/num4.png"))); // NOI18N
        btnCuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuatroActionPerformed(evt);
            }
        });
        jPanel1.add(btnCuatro, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 48, 48));

        btnCinco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/num5.png"))); // NOI18N
        btnCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCincoActionPerformed(evt);
            }
        });
        jPanel1.add(btnCinco, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 48, 48));

        btnSeis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/num6.png"))); // NOI18N
        btnSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeisActionPerformed(evt);
            }
        });
        jPanel1.add(btnSeis, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 48, 48));

        btnSiete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/num7.png"))); // NOI18N
        btnSiete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSieteActionPerformed(evt);
            }
        });
        jPanel1.add(btnSiete, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 48, 48));

        btnOcho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/num8.png"))); // NOI18N
        btnOcho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOchoActionPerformed(evt);
            }
        });
        jPanel1.add(btnOcho, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 48, 48));

        btnNueve.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/num9.png"))); // NOI18N
        btnNueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNueveActionPerformed(evt);
            }
        });
        jPanel1.add(btnNueve, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 48, 48));

        btnSuma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/suma.png"))); // NOI18N
        btnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaActionPerformed(evt);
            }
        });
        jPanel1.add(btnSuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 48, 48));

        btnMultiplicacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/multiplicacion.png"))); // NOI18N
        btnMultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicacionActionPerformed(evt);
            }
        });
        jPanel1.add(btnMultiplicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 48, 48));

        btnDividir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/dividir.png"))); // NOI18N
        btnDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDividirActionPerformed(evt);
            }
        });
        jPanel1.add(btnDividir, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 48, 48));

        btnCero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/num0.png"))); // NOI18N
        btnCero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCeroActionPerformed(evt);
            }
        });
        jPanel1.add(btnCero, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 48, 48));

        btnResta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/resta.png"))); // NOI18N
        btnResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaActionPerformed(evt);
            }
        });
        jPanel1.add(btnResta, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 48, 48));

        btnResultado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/signo-igual.png"))); // NOI18N
        btnResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultadoActionPerformed(evt);
            }
        });
        jPanel1.add(btnResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 48, 48));

        btnBorrarUnDigito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/FlechaIzq.png"))); // NOI18N
        btnBorrarUnDigito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarUnDigitoActionPerformed(evt);
            }
        });
        jPanel1.add(btnBorrarUnDigito, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 48, 48));

        btnPuntoDecimal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/punto.png"))); // NOI18N
        btnPuntoDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuntoDecimalActionPerformed(evt);
            }
        });
        jPanel1.add(btnPuntoDecimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 48, 48));

        lblSimbolo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons8-sombrero-45.png"))); // NOI18N
        jPanel1.add(lblSimbolo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, 48, 48));

        FondoColor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Witching Hour.png"))); // NOI18N
        jPanel1.add(FondoColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPantallaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPantallaKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9'))
            evt.consume();
    }//GEN-LAST:event_txtPantallaKeyTyped

    public void agregarNum(String num) {
        // agrega un numeor 
        if (operacionRealizada) {
            operacionRealizada = false;
            txtPantalla.setText("");

        }
        txtPantalla.setText(txtPantalla.getText() + num);

    }


    private void btnUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnoActionPerformed
        // TODO add your handling code here:
        agregarNum("1");

    }//GEN-LAST:event_btnUnoActionPerformed

    private void btnDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDosActionPerformed
        // TODO add your handling code here:
        agregarNum("2");
    }//GEN-LAST:event_btnDosActionPerformed

    private void btnTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTresActionPerformed
        // TODO add your handling code here:
        agregarNum("3");
    }//GEN-LAST:event_btnTresActionPerformed

    private void btnCuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuatroActionPerformed
        // TODO add your handling code here:
        agregarNum("4");
    }//GEN-LAST:event_btnCuatroActionPerformed

    private void btnCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCincoActionPerformed
        // TODO add your handling code here:
        agregarNum("5");
    }//GEN-LAST:event_btnCincoActionPerformed

    private void btnSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeisActionPerformed
        // TODO add your handling code here:
        agregarNum("6");
    }//GEN-LAST:event_btnSeisActionPerformed

    private void btnSieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSieteActionPerformed
        // TODO add your handling code here:
        agregarNum("7");
    }//GEN-LAST:event_btnSieteActionPerformed

    private void btnOchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOchoActionPerformed
        // TODO add your handling code here:
        agregarNum("8");
    }//GEN-LAST:event_btnOchoActionPerformed

    private void btnNueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNueveActionPerformed
        // TODO add your handling code here:
        agregarNum("9");
    }//GEN-LAST:event_btnNueveActionPerformed

    private void btnCeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCeroActionPerformed
        // TODO add your handling code here:
        agregarNum("0");
    }//GEN-LAST:event_btnCeroActionPerformed


    private void btnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaActionPerformed
        // TODO add your handling code here:
        if (!txtPantalla.getText().equals("")) {
            System.out.println("calculadora.jfPrincipal.btnSumaActionPerformed()");
            operacion.setNumero1(Float.parseFloat(txtPantalla.getText()));
            operacion.suma();
            if (operacion.getOperacionAntes() != '+') {
                operacion.setOperacionAntes('+');
            }
            operacionRealizada = true;

        }
    }//GEN-LAST:event_btnSumaActionPerformed

    private void btnResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultadoActionPerformed
        // TODO add your handling code here

        if (!txtPantalla.getText().equals("")) {
            operacion.setNumero1(Float.parseFloat(txtPantalla.getText()));
            // operacion.setNumero2(Float.parseFloat(txtPantalla.getText()));
            operacion.operacionAnterior();
        }

        txtPantalla.setText(String.valueOf(operacion.getResultados()));
        operacionRealizada = false;
    }//GEN-LAST:event_btnResultadoActionPerformed


    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
        // TODO add your handling code here:
        // borra y reinica todo los sistemas 
        operacion.setResultados(0);
        operacion.setNumero1(0);
        operacion.setOperacionAntes(' ');
        txtPantalla.setText("");


    }//GEN-LAST:event_btnCActionPerformed

    private void btnRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaActionPerformed
        if (!txtPantalla.getText().equals("")) {
            operacion.setNumero1(Float.parseFloat(txtPantalla.getText()));
            operacion.resta();
            if (operacion.getOperacionAntes() != '-') {
                operacion.setOperacionAntes('-');
            }
            operacionRealizada = true;
        }
    }//GEN-LAST:event_btnRestaActionPerformed

    private void btnMultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicacionActionPerformed
        // TODO add your handling code here:
        if (!txtPantalla.getText().equals("")) {
            if (operacion.getResultados() == 0) {
                operacion.setResultados(1);
            }
            operacion.setNumero1(Float.parseFloat(txtPantalla.getText()));
            operacion.multiplicacion();
            if (operacion.getOperacionAntes() != 'x') {
                operacion.setOperacionAntes('x');
            }
            operacionRealizada = true;
        }
    }//GEN-LAST:event_btnMultiplicacionActionPerformed

    private void btnDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDividirActionPerformed
        if (!txtPantalla.getText().equals("")) {
            if (operacion.getResultados() == 0) {
                operacion.setResultados(1);
            }
            operacion.setNumero1(Float.parseFloat(txtPantalla.getText()));
            operacion.divicion();
            if (operacion.getOperacionAntes() != '/') {
                operacion.setOperacionAntes('/');
            }
            operacionRealizada = true;
        }
    }//GEN-LAST:event_btnDividirActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // Antes de cerra la ventana manda un mensaje de advertencia 
        cerrar();
    }//GEN-LAST:event_formWindowClosing

    private void btnBorrarUnDigitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarUnDigitoActionPerformed
        // Borra un digito a al vez
        String m = txtPantalla.getText();
        if (!m.equals("")) {
            m = m.substring(0, m.length() - 1);
            txtPantalla.setText(m);
        }


    }//GEN-LAST:event_btnBorrarUnDigitoActionPerformed

    private void btnPuntoDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuntoDecimalActionPerformed
        // TODO add your handling code here:
        if (existenciaPunto()) {
            // Agrega y verifica un punto 
            agregarNum(".");
        }
    }//GEN-LAST:event_btnPuntoDecimalActionPerformed

    public boolean existenciaPunto() {
        // Verifica que no exita un punto antes
        boolean respuesta = true;
        if (!txtPantalla.getText().equals("")) {
            for (int i = 0; i < txtPantalla.getText().length(); i++) {
                char letra = txtPantalla.getText().charAt(i);
                if (letra == '.') {
                    respuesta = false;
                    break;
                }
            }
        } else {
            respuesta = false;
        }

        return respuesta;
    }

    private boolean verficacion() {
        // Verifica qu no dejemos campos vacios 
        boolean respuesta = true;
        if (txtPantalla.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "No dejar campos Vacíos", "Error!", JOptionPane.ERROR_MESSAGE);
            respuesta = false;
        }
        return respuesta;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfPrincipal().setVisible(true);
            }
        });

//        try {
//
//            JFrame.setDefaultLookAndFeelDecorated(true);
//            JDialog.setDefaultLookAndFeelDecorated(true);
//            //UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
//            //UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
//            //UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
//            //UIManager.setLookAndFeel("com.sun.java.swing.plaf.motif.MotifLookAndFeel");
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoColor;
    private javax.swing.JButton btnBorrarUnDigito;
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnCero;
    private javax.swing.JButton btnCinco;
    private javax.swing.JButton btnCuatro;
    private javax.swing.JButton btnDividir;
    private javax.swing.JButton btnDos;
    private javax.swing.JButton btnMultiplicacion;
    private javax.swing.JButton btnNueve;
    private javax.swing.JButton btnOcho;
    private javax.swing.JButton btnPuntoDecimal;
    private javax.swing.JButton btnResta;
    private javax.swing.JButton btnResultado;
    private javax.swing.JButton btnSeis;
    private javax.swing.JButton btnSiete;
    private javax.swing.JButton btnSuma;
    private javax.swing.JButton btnTres;
    private javax.swing.JButton btnUno;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblSimbolo;
    private javax.swing.JTextField txtPantalla;
    // End of variables declaration//GEN-END:variables
}
